site_name: Ryderz Roleplay
site_description: "Wet en regelgeving van Ryderz roleplay"
site_url: https://apv.ryderzrp.nl

repo_url: "https://github.com/Ryderzroleplay/Ryderz-roleplay"
repo_name: "Ryderz Roleplay"

nav:
  - Home: index.md
  - Ryderz Team: team.md
  - Algemene Regels: algemeen.md
  - Onderwereld Regels: onderwereld.md
  - Overheid: overheid.md   # maak deze pagina aan, of pas het pad aan

theme:
  name: material
  language: nl
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/akvhh7dREq
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@rdyzmo
  analytics:
    provider: google
    property: G-NV5M4K299L
  consent:
    title: Cookies
    description: >-
      We gebruiken cookies om uw herhaalde bezoeken en voorkeuren te herkennen, en
      om de effectiviteit van onze documentatie te meten en of gebruikers
      vinden wat ze zoeken. Met uw toestemming helpt u ons om
      onze documentatie te verbeteren.
    actions:
      - accept

copyright: Copyright &copy; 2025 Ryderz Roleplay - Alle rechten voorbehouden.

plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl

extra_css:
  - styles.css?v=2
